x-base-steps: &base-steps
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
    with:
      node-version: 'lts'
      cache: 'yarn'
  - run: yarn install

name: Lint on requests
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - <<: *base-steps
      - run: yarn lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - <<: *base-steps
      - run: yarn lint
